version: '3'

services:
  db:
    image: postgres:10
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    image: redis:alpine
    ports:
      - 6379
    networks:
      - backend
    restart: unless-stopped

  geoip:
    image: cryptlex/freegeoip:3.5.0
    ports:
      - 8080
    networks:
      - backend
    restart: unless-stopped

  loadbalancer: 
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - APPLICATION_URL=${WEB_API_URL}
    depends_on:
      - webapi
    ports:
      - 80:80
      - 443:443
    networks:
      - backend
    restart: unless-stopped

  webapi:
    image: cryptlex/cryptlex-web-api-enterprise:3.10.1
    depends_on:
      - db
      - geoip
    env_file: webapi.env
    networks:
      - backend
    restart: unless-stopped
    ports:
      - 5000

  webapp:
    image: cryptlex/cryptlex-web-app-enterprise:3.0.0
    depends_on:
      - webapi
    environment:
      COMPANY_NAME: "My Company"
      COMPANY_WEBSITE: http://mycompany.com
      WEB_API_BASE_URL: ${WEB_API_URL}
      GOOGLE_ANALYTICS_KEY: UA-XXXXXXXX-X
    networks:
      - frontend
    restart: unless-stopped
    ports:
      - 4200:80

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  db_data: