version: '3'

services:
  database:
    image: postgres:10.7-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432
    networks:
      - backend
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
    volumes:
      - db_data:/var/lib/postgresql/data
    labels:
      - traefik.enable=false

  filestore:
    image: minio/minio:RELEASE.2019-02-26T19-51-46Z
    environment:
      MINIO_ACCESS_KEY: ${FILE_STORE_ACCESS_KEY}
      MINIO_SECRET_KEY: ${FILE_STORE_SECRET_KEY}
    command: server http://filestore/data
    ports:
      - 9000
    networks:
      - backend
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
    volumes:
      - filestore_data:/data
    labels:
      - traefik.enable=false

  geoip:
    image: cryptlex/freegeoip:3.6.0
    ports:
      - 8080
    networks:
      - backend
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
    labels:
      - traefik.enable=false
  
  reverse-proxy:
    image: traefik:1.7-alpine
    command: --api --docker --logLevel=INFO --acme.email=${EMAIL}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    expose:
      # traefik dashboard port
      - 8080
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:${DASHBOARD_DOMAIN};PathPrefixStrip:/traefik
      - traefik.port=8080
      - traefik.frontend.auth.basic.users=[${TRAEFIK_BASIC_AUTH}]
    networks:
      - backend
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"

  # not required for single machine deployment
  # cache:
  #   image: redis:alpine
  #   ports:
  #     - 6379
  #   networks:
  #     - backend
  #   restart: unless-stopped
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "20m"
  #   labels:
  #     - traefik.enable=false

  webapi:
    image: cryptlex/cryptlex-web-api-enterprise:latest
    depends_on:
      - db
      - geoip
    env_file: webapi.env
    environment:
      JWT_AUDIENCE: http://webapi:5000
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: # redis://cache:6379 - not required for single machine deployment
      GEOIPSERVER_URL: http://geoip:8080/json
    networks:
      - backend
    restart: unless-stopped
    ports:
      - 5000
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
    labels:
      - traefik.backend=cryptlex-webapi
      - traefik.frontend.rule=Host:${WEB_API_DOMAIN}
      - traefik.frontend.passHostHeader=true
      - traefik.docker.network=backend
      - traefik.port=5000

  dashboard:
    image: cryptlex/cryptlex-web-dashboard:latest
    depends_on:
      - webapi
    env_file: dashboard.env
    environment:
      WEB_API_BASE_URL: https://${WEB_API_DOMAIN}
    networks:
      - backend
    restart: unless-stopped
    ports:
      - 4200
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
    labels:
      - traefik.backend=cryptlex-dashboard
      - traefik.frontend.rule=Host:${DASHBOARD_DOMAIN}
      - traefik.docker.network=backend
      - traefik.port=4200

  release-server:
    image: cryptlex/cryptlex-release-server:3.0.0
    depends_on:
      - webapi
    env_file: release-server.env
    environment:
      WEB_API_BASE_URL: https://${WEB_API_DOMAIN}
      RELEASE_SERVER_BASE_URL: https://${RELEASE_SERVER_DOMAIN}
      FILE_STORE_ACCESS_KEY: ${FILE_STORE_ACCESS_KEY}
      FILE_STORE_SECRET_KEY: ${FILE_STORE_SECRET_KEY}
      FILE_STORE_ENDPOINT: filestore
      FILE_STORE_PORT: 9000
    networks:
      - backend
    restart: unless-stopped
    ports:
      - 3000
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
    labels:
      - traefik.backend=cryptlex-release-server
      - traefik.frontend.rule=Host:${RELEASE_SERVER_DOMAIN}
      - traefik.docker.network=backend
      - traefik.port=3000

networks:
  backend:
    driver: bridge

volumes:
  db_data:
